module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#00488d',
          container: '#d6e3ff',
          fixed: 'd6e3ff',
          'fixed-dim': 'b7cff0',
        },
        secondary: {
          DEFAULT: '#6c5ce7',
          container: '#eaddff',
          fixed: 'eaddff',
          'fixed-dim': 'dcc8f8',
        },
        tertiary: {
          DEFAULT: '#00a86b',
          container: 'b8f0c5',
          fixed: 'b8f0c5',
          'fixed-dim': '9cd9ad',
        },
        surface: '#fffbfe',
        'surface-container-lowest': '#fffbfe',
        'surface-container-low': '#fdf8fd',
        'surface-container': '#f7eff4',
        'surface-container-high': '#f1eaf1',
        'surface-container-highest': '#ebe5eb',
        'surface-dim': '#ede8ed',
        'surface-bright': '#fffbfe',
        'surface-variant': '#e7e0eb',
        'on-surface': '#191c21',
        'on-surface-variant': '#49454e',
        'outline': '#79747e',
        'outline-variant': '#cac4cf',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        xs: ['12px', '16px'],
        sm: ['14px', '20px'],
        base: ['16px', '24px'],
        lg: ['18px', '28px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['28px', '36px'],
        '4xl': ['32px', '40px'],
        '5xl': ['40px', '48px'],
      },
      boxShadow: {
        sm: '0 2px 4px rgba(0, 0, 0, 0.05)',
        DEFAULT: '0 4px 8px rgba(0, 0, 0, 0.1)',
        md: '0 8px 16px rgba(0, 0, 0, 0.1)',
        lg: '0 12px 24px rgba(0, 0, 0, 0.15)',
        xl: '0 16px 32px rgba(0, 0, 0, 0.2)',
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '28px',
      },
    },
  },
  plugins: [],
}
